ProductCatalog/Models/Category.cs
using ProductCatalog.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ProductCatalog.Models
{
    [Table("CATEGORIES")]
    public class Category
    {
        [Key]
        public int CategoryId { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}

ProductCatalog/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ProductCatalog.Models
{
    [Table("PRODUCTS")]
    public class Product
    {
        [Key]
        [Display(Name ="ID")]
        public int ProductId { get; set; }
        [StringLength(50), Required]
        public string Designation { get; set; }
        [Range(0, 1000000), Required]
        public double Price { get; set; }
        [Required]
        public int CategoryId { get; set; }
        [ForeignKey("CategoryId")]
        public virtual Category Category { get; set; }
    }
}

ProductCatalog/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ProductCatalog.Interfaces;
using ProductCatalog.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace ProductCatalog.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService CategoryService;

        public CategoryController(ICategoryService CategoryService)
        {
            this.CategoryService = CategoryService;
        }

        // GET: /<controller>/
        public IActionResult Index(int page = 0, int size = 5)
        {
            int pos = page * size;
            int totalCategory = CategoryService.FindAll().Count();
            int totalPages = totalCategory / size;
            if (totalCategory % size != 0)
            {
                totalPages += 1;
            }
            ViewBag.CurrentPage = page;
            ViewBag.totalPages = totalPages;
            IEnumerable<Category> categories = CategoryService
                                                .FindAll()
                                                .Skip(pos)
                                                .Take(size)
                                                .ToList();
            return View("Categories", categories);
        }

        public IActionResult CategoryForm()
        {
            Category c = new Category();
            return View("CategoryForm", c);

        }

        [HttpPost]
        public IActionResult SaveCategory(Category c)
        {

            if (ModelState.IsValid)
            {
                CategoryService.Save(c);
                return RedirectToAction("Index");
            }
            return View("CategoryForm", c);

        }

        [HttpPost]
        public ActionResult DeleteCategory(IFormCollection form)
        {
            int id = Convert.ToInt32(form["DeletedCategoryId"]);
            CategoryService.Delete(id);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult UpdateCategory(IFormCollection form)
        {
            CategoryService.Update(form);
            return RedirectToAction("Index");
        }
    }
}

ProductCatalog/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ProductCatalog.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

ProductCatalog/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProductCatalog.Interfaces;
using ProductCatalog.Models;
using ProductCatalog.Service;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace ProductCatalog.Controllers
{
    public class ProductController : Controller
    {

        private readonly IProductService ProductService;
        private readonly ICategoryService CategoryService;

        public ProductController(IProductService ProductService,
                                 ICategoryService CategoryService)
        {
            this.ProductService = ProductService;
            this.CategoryService = CategoryService;
        }
        

        // GET: /<controller>/
        public IActionResult Index(int page = 0, int size = 5, string keyword = "")
        {
            int pos = page * size;
            if (keyword == null) keyword = "";
            int totalProduct = ProductService.FindAll().Where(p => p.Designation.Contains(keyword)).Count();
            int totalPages = totalProduct / size;
            if (totalProduct%size!=0) {
                totalPages += 1;
            }
            ViewBag.CurrentPage = page;
            ViewBag.totalPages = totalPages;
            IEnumerable<Category> categories = CategoryService.FindAll();
            ViewBag.categories = categories;
            ViewBag.keyword = keyword;
            IEnumerable<Product> products = ProductService
                                            .FindAll()
                                            .Where(p=>p.Designation.Contains(keyword))
                                            .Skip(pos)
                                            .Take(size)
                                            .ToList();
            return View("Products", products);
        }

        public IActionResult ProductForm()
        {
            Product prod = new Product();
            IEnumerable<Category> categories = CategoryService.FindAll().ToList();
            ViewBag.categories = categories;
            return View("ProductForm", prod);

        }
        [HttpPost]
        public IActionResult Save(Product prod)
        {
            
            if (ModelState.IsValid) {
                ProductService.Save(prod);
                return RedirectToAction("Index");
            }
            IEnumerable<Category> categories = CategoryService.FindAll().ToList();
            ViewBag.categories = categories;
            return View("ProductForm", prod);

        }

        [HttpPost]
        public ActionResult DeleteConfirmed(IFormCollection  form)
        {
            int id = Convert.ToInt32(form["DeletedProductId"]);
            ProductService.Delete(id);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Update(IFormCollection form)
        {
            ProductService.Update(form);
            return RedirectToAction("Index");
        }
    }
}

ProductCatalog/Views/Category/Categories.cshtml
@model IEnumerable<ProductCatalog.Models.Category>
<p></p>
<div class="container-fluid">
    <p></p>
    <a class="btn btn-warning" asp-action="CategoryForm">New Category</a>
    <p></p>
    <div class="panel panel-warning">
        <p></p>
        <div class="panel-heading">Category list</div>
        <div class="panel-body">
            <table class="table table-bordered table-responsive table-striped">
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                </tr>
                @{
                    foreach (var c in Model)
                    {
                        <tr>
                            <td id="prdId">@c.CategoryId</td>
                            <td>@c.Name</td>
                            <td> <a class="btn btn-primary UpdateCategoryDialog" data-toggle="modal" data-target="#update_categ" data-categ-id="@c.CategoryId" data-name="@c.Name"><span class="glyphicon glyphicon-edit"></span></a></td>
                            <td> <a class="btn btn-danger DeleteCategoryDialog" data-toggle="modal" data-target="#delete_categ" data-id="@c.CategoryId"><span class="glyphicon glyphicon-trash"></span></a></td>
                        </tr>
                    }
                }
            </table>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <ul class="nav nav-pills">
                    @{
                        for (int i = 0; i < ViewBag.totalPages; i++)
                        {
                            string className = "";
                            if (i == ViewBag.CurrentPage)
                            {
                                className = "active";
                            }
                            <li class="@className">
                                <a asp-action="Index" asp-route-page="@i">@(i + 1)</a>
                            </li>
                        }
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="modal fade" tabindex="-1" role="dialog" id="delete_categ">
        <div class="modal-dialog modal-dialog-centered" role="dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button class="close" data-dismiss="modal">×</button>
                    <h3 class="h3 text-center">Delete Action</h3>
                </div>
                <div class="modal-body" id="modal-body-delete-category">
                    <h3 class="h3 text-center">You are about to delete a category of id :</h3>
                    <h3 class="h3 text-center" id="DeletedCategoryId2"></h3>
                    <form method="post" asp-action="DeleteCategory">
                        <input type="hidden" name="DeletedCategoryId" id="DeletedCategoryId" />
                        <button class="btn btn-warning" type="submit">Delete</button>
                    </form>
                </div>
                <div class="modal-footer">

                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" tabindex="-1" role="dialog" id="update_categ">
        <div class="modal-dialog modal-dialog-centered" role="dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button class="close" data-dismiss="modal">×</button>
                    <h3 class="h3 text-center">Update Action</h3>
                </div>
                <div class="modal-body" id="modal-body-update-category">
                    <h3 class="h3 text-center">You are about to update a category</h3>
                    <form method="post" asp-action="UpdateCategory">
                        <input type="hidden" id="updatedCategoryId" name="Id" />
                        <div class="form-group">
                            <label class="control-label">Name:</label>
                            <input type="text" class="form-control" name="Name" id="updatedName" required />
                        </div>
                        <div>
                            <button class="btn btn-primary" type="submit">Save changes</button>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">

                </div>
            </div>
        </div>
    </div>
</div>

ProductCatalog/Views/Category/CategoryForm.cshtml
@model ProductCatalog.Models.Category
@{
    ViewData["title"] = "add new category";
}
<p></p>
<div class="panel panel-warning">
    <p></p>
    <div class="panel-heading">new Category</div>
    <div class="panel-body">
        <form method="post" asp-action="SaveCategory">
            <div class="form-group">
                @Html.LabelFor(c => c.Name, new { @class = "control-label" })
                @Html.TextBoxFor(c => c.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(c => c.Name, "", new { @class = "text-danger" })
            </div>
            <div>
                <input class="btn btn-warning" type="submit" value="Save" />
            </div>
        </form>
    </div>
</div>

ProductCatalog/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

ProductCatalog/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ProductCatalog/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet, Bower, and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518004">Bower</a> for managing client-side libraries</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699318">Add client packages using Bower.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

ProductCatalog/Views/Product/ProductForm.cshtml
@model ProductCatalog.Models.Product
@{ 
    ViewData["title"] = "add new product";
}
<p></p>
<div class="panel panel-default">
    <p></p>
    <div class="panel-heading">new Product</div>
    <div class="panel-body">
        <form method="post" asp-action="Save">
            <div class="form-group">
                @Html.LabelFor(prod => prod.Designation, new { @class = "control-label" })
                @Html.TextBoxFor(prod => prod.Designation, new { @class = "form-control" })
                @Html.ValidationMessageFor(prod => prod.Designation, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(prod => prod.Price, new { @class = "control-label" })
                @Html.TextBoxFor(prod => prod.Price, new { @class = "form-control" })
                @Html.ValidationMessageFor(prod => prod.Price, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(prod => prod.Category, new { @class = "control-label" })
                @Html.DropDownListFor(prod => prod.CategoryId,
                         new SelectList(ViewBag.categories, "CategoryId", "Name"))
                @Html.ValidationMessageFor(prod => prod.CategoryId, "", new { @class = "text-danger" })
            </div>
            <div>
                <input class="btn btn-default" type="submit" value="Save" />
            </div>
        </form>
    </div>
</div>

ProductCatalog/Views/Product/Products.cshtml
@model IEnumerable<ProductCatalog.Models.Product>
<p></p>
<div class="container-fluid">
    <p></p>
    <a class="btn btn-default" asp-action="ProductForm">Add new Product</a>
    <p></p>
    <div class="panel panel-default">
        <p></p>
        <div class="panel-heading">Products list</div>
        <div class="panel-body">
            <p></p>
            <div class="container">
                <form method="get" asp-action="Index">
                    <div class="form-group">
                        <label for="keyword" class="control-label">Search: </label>
                        <input type="text" name="keyword" id="keyword" />
                        <button class="btn btn-default btn-sm" type="submit"><span class="glyphicon glyphicon-search"></span></button>
                    </div>
                </form>
            </div>
            <p></p>
            <table class="table table-bordered table-responsive table-striped">
                <tr>
                    <th>ID</th>
                    <th>DESIGNATION</th>
                    <th>PRICE</th>
                    <th>CATEGORY ID</th>
                </tr>
                @{
                    foreach (var prod in Model)
                    {
                        <tr>
                            <td id="prdId">@prod.ProductId</td>
                            <td>@prod.Designation</td>
                            <td>@prod.Price</td>
                            <td>@prod.Category.Name</td>
                            <td> <a class="btn btn-primary UpdateProductDialog" data-toggle="modal" data-target="#update_prod" data-prod-id="@prod.ProductId" data-desig="@prod.Designation" data-price="@prod.Price" data-categ="@prod.CategoryId" ><span class="glyphicon glyphicon-edit"></span></a></td>
                            <td> <a class="btn btn-danger DeleteProductDialog" data-toggle="modal" data-target="#delete_prod" data-id="@prod.ProductId"><span class="glyphicon glyphicon-trash"></span></a></td>
                        </tr>
                    }
                }
            </table>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <ul class="nav nav-pills">
                    @{
                        for (int i = 0; i < ViewBag.totalPages; i++)
                        {
                            string className = "";
                            if (i == ViewBag.CurrentPage)
                            {
                                className = "active";
                            }
                            <li class="@className">
                                <a asp-action="Index" asp-route-page="@i" asp-route-keyword="@ViewBag.keyword">@(i + 1)</a>
                            </li>
                        }
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="modal fade" tabindex="-1" role="dialog" id="delete_prod">
        <div class="modal-dialog modal-dialog-centered" role="dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button class="close" data-dismiss="modal">×</button>
                    <h3 class="h3 text-center">Delete Action</h3>
                </div>
                <div class="modal-body" id="modal-body-delete-product">
                    <h3 class="h3 text-center">You are about to delete the product of id: </h3>
                    <h3 class="h3 text-center" id="DeletedProductId2"></h3>
                    <form method="post" asp-action="DeleteConfirmed">
                        <input type="hidden" name="DeletedProductId" id="DeletedProductId" />
                        <button class="btn btn-warning" type="submit">Delete</button>
                    </form>
                </div>
                <div class="modal-footer">

                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" tabindex="-1" role="dialog" id="update_prod">
        <div class="modal-dialog modal-dialog-centered" role="dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button class="close" data-dismiss="modal">×</button>
                    <h3 class="h3 text-center">Update Action</h3>
                </div>
                <div class="modal-body" id="modal-body-update-product">
                    <h3 class="h3 text-center">You are about to update a product</h3>
                    <form method="post" asp-action="Update">
                        <input type="hidden" id="updatedProductId" name="Id" />
                        <div class="form-group">
                            <label class="control-label">Designation:</label>
                            <input type="text" class="form-control" name="Designation" id="updatedDesignation" required />
                        </div>
                        <div class="form-group">
                            <label class="control-label">Price:</label>
                            <input type="text" class="form-control" name="Price" id="updatedPrice" required />
                        </div>
                        <div class="form-group">
                            <label class="control-label">Category:</label>
                            <select data-val="true" data-val-required="Le champ CategoryId est requis." id="updatedCategoryId" name="CategoryId">
                                @{
                                    foreach (var Category in ViewBag.categories)
                                    {
                                        <option value="@Category.CategoryId">@Category.Name</option>
                                    }
                                }
                            </select>
                        </div>
                        <div>
                            <button class="btn btn-primary" type="submit">Save changes</button>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    
                </div>
            </div>
        </div>
    </div>
</div>

ProductCatalog/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProductCatalog</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">ProductCatalog</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Product" asp-action="Index">Products</a></li>
                    <li><a asp-area="" asp-controller="Category" asp-action="Index">Categories</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - ProductCatalog</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>